name: Build and Deploy Resume

on:
  push:
    branches:
      - main # Change to 'master' if your main branch is called master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Prepare Deployment Folder
        run: |
          mkdir public
          cp main.pdf public/resume.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
